# Generated by Django 3.0.5 on 2020-04-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algo',
            name='code',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
    ]
